import { NextResponse } from "next/server"

const STABILITY_API_KEY = process.env.STABILITY_API_KEY
const STABILITY_API_URL = "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/image-to-image"

export async function POST(req: Request) {
  if (!STABILITY_API_KEY) {
    console.error("Stability API key is not set")
    return NextResponse.json({ error: "Stability API key not configured" }, { status: 500 })
  }

  try {
    const formData = await req.formData()
    const image = formData.get("image") as File
    const preferences = formData.get("preferences") as string

    if (!image || !preferences) {
      return NextResponse.json({ error: "Missing image or preferences" }, { status: 400 })
    }

    const imageBuffer = await image.arrayBuffer()

    const response = await fetch(STABILITY_API_URL, {
      method: "POST",
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${STABILITY_API_KEY}`,
      },
      body: (() => {
        const formData = new FormData()
        formData.append("init_image", new Blob([imageBuffer]), "room.jpg")
        formData.append(
          "text_prompts[0][text]",
          `Transform this room into a nursery with the following design: ${preferences}`,
        )
        formData.append("cfg_scale", "7")
        formData.append("clip_guidance_preset", "FAST_BLUE")
        formData.append("samples", "1")
        formData.append("steps", "30")
        return formData
      })(),
    })

    if (!response.ok) {
      const errorData = await response.json()
      console.error("Stability AI API error:", errorData)
      throw new Error(errorData.message || "Failed to generate nursery design")
    }

    const responseData = await response.json()

    if (!responseData.artifacts || responseData.artifacts.length === 0) {
      throw new Error("No image generated by Stability AI")
    }

    const generatedImageBase64 = responseData.artifacts[0].base64

    return NextResponse.json({ output_url: `data:image/png;base64,${generatedImageBase64}` })
  } catch (error: any) {
    console.error(`Error with Stability AI API request:`, error)
    return NextResponse.json(
      { error: error.message || "An error occurred during your request." },
      { status: error.status || 500 },
    )
  }
}

